# Generated by Django 4.2 on 2025-02-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.EmailField(max_length=50, unique=True)),
                ('descripcio', models.CharField(max_length=20)),
                ('preu', models.CharField(max_length=20)),
                ('stock', models.CharField(max_length=15)),
                ('categoria', models.CharField(max_length=15)),
                ('imatge', models.CharField(max_length=15)),
            ],
        ),
    ]
